version: '2'
services:
    xiaobaolife-app:
        image: xiaobaolife
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xiaobaolife-mysql:3306/xiaobaolife?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    xiaobaolife-mysql:
        extends:
            file: mysql.yml
            service: xiaobaolife-mysql
